title: ptrs service status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.ptr.gg
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: ptr.gg - Frontend
      description: ptr.gg portfolio and web frontend
      category: Primary Access Server
      link: https://example.com/
      partial: ""
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/apple-touch-icon-114x114.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: yearly
  disableIncidentHistory: false
  ok: "#008000"
  categories:
    - name: Primary Access Server
      description: Primary web service provision server
      closed: true
    - name: Secondary Web Host
      description: Secondary webpage provision host
      closed: true
  description: Status page is automatically updated and hosted independtly from
    any listed services.
  enableCustomHTML: true
  useLargeHeaderDesign: false
