title: ptrs service status
buildFuture: true
defaultContentLanguage: en
languageCode: en
baseURL: https://status.ptr.gg
theme: cstate
preserveTaxonomyNames: true
taxonomies:
  affected: affected
outputs:
  page:
    - html
    - json
  section:
    - html
    - json
    - rss
  home:
    - html
    - json
    - rss
    - svg
  term:
    - html
    - json
    - rss
    - svg
outputFormats:
  svg:
    isPlainText: true
    mediaType: image/svg+xml
enableGitInfo: true
params:
  skipSeconds: false
  useRelativeTime: true
  disableDarkMode: false
  shortDateFormat: 15:04 UTC — Jan 2
  down: "#e60000"
  systems:
    - name: ptr.gg
      description: ptr.gg portfolio and web frontend
      category: Alpha Server
      link: https://example.com/
      partial: ""
    - name: ptrs.xyz
      category: Beta Server
      description: ptrs.xyz personal portfolio web frontend
    - name: birdly.uk
      category: Beta Server
      description: birdly.uk political blog web frontend
    - name: cloud.ptr.gg
      category: Alpha Server
      description: ptr.gg cloud service provider
    - name: filehost.ptr.gg
      category: Alpha Server
      description: File hosting backend
    - name: url.ptr.gg
      category: Alpha Server
      description: Custom URL shortening service
    - name: ptrs Email Service
      category: Other
      description: ptrs email provider
  dateFormat: January 2, 2006 at 3:04 PM UTC
  brand: "#0a0c0f"
  enableLastMod: true
  headerTextColor: white
  logo: /img/apple-touch-icon-114x114.png
  incidentPostsPerPage: 10
  googleAnalytics: UA-00000000-1
  alwaysKeepBrandColor: true
  disableComplexCalculations: false
  useLogo: true
  disrupted: "#cc4400"
  notice: "#24478f"
  incidentHistoryFormat: monthly
  disableIncidentHistory: true
  ok: "#008000"
  categories:
    - name: Alpha Server
      description: Primary web service provision server
      closed: false
    - name: Beta Server
      description: Secondary web service provision server
      closed: false
    - name: Other
      description: External and other services
      closed: true
  description: Status page is manually upadted and hosted with redundancy and
    independently from any listed services.
  enableCustomHTML: true
  useLargeHeaderDesign: false
